# Generated by Django 2.1.4 on 2019-01-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190105_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
