# Generated by Django 2.1.4 on 2019-02-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0011_profile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('website', models.URLField(blank=True, verbose_name='網站')),
                ('personalprofile', models.TextField(blank=True, max_length=300, verbose_name='個人簡介')),
                ('phonenumber', models.CharField(blank=True, max_length=30, verbose_name='電話號碼')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
