# Generated by Django 2.1.4 on 2019-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190218_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personalprofile',
            field=models.TextField(blank=True, max_length=300, verbose_name='個人簡介'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話號碼'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='網站'),
        ),
        migrations.DeleteModel(
            name='OtherProfile',
        ),
    ]
