# Generated by Django 2.1.4 on 2019-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190223_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
