# Generated by Django 2.1.4 on 2019-02-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190223_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='personalprofile',
            new_name='personal_profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
