# Generated by Django 2.1.4 on 2019-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20190313_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性'), ('N', '未指定')], default='N', max_length=10, verbose_name='性別'),
        ),
    ]
