# Generated by Django 2.1.4 on 2019-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20190313_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='https://raw.githubusercontent.com/v8661087/v8661087.github.io/master/media/users/default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
