# Generated by Django 2.1.4 on 2019-01-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='相片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, verbose_name='標題'),
        ),
    ]
