# Generated by Django 2.1.4 on 2019-01-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190123_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
