# Generated by Django 2.1.4 on 2019-01-23 08:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20190123_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[600, 600], upload_to='images/%Y/%m/%d', verbose_name='相片'),
        ),
    ]
