# Generated by Django 2.1.4 on 2019-01-23 08:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20190123_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[600, 600], upload_to='images/%Y/%m/%d', verbose_name='相片'),
        ),
    ]
