# Generated by Django 2.1.4 on 2019-03-07 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0015_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='saved_image',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='users_save',
            field=models.ManyToManyField(blank=True, related_name='images_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
