# Generated by Django 2.1.4 on 2019-03-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20190315_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(verbose_name='網址'),
        ),
    ]
